name: fitness
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  
  
  flutter:
    sdk: flutter
  simple_circular_progress_bar: ^1.0.2
  syncfusion_flutter_charts: ^21.1.41
  fancy_bottom_navigation: ^0.3.2
  
  pie_chart: ^5.3.2
  charts_flutter: ^0.12.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.60.0
  numberpicker: ^2.1.1
  vertical_weight_slider: ^2.5.0
  page_view_indicators: ^2.0.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.1
  convex_bottom_bar: ^3.2.0
  fluttertoast: ^8.2.1


  #fire base
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  syncfusion_flutter_gauges: ^21.1.35
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
